/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface IPWNSimpleLoanInterface extends utils.Interface {
  functions: {
    "createLOAN(address,bytes,bytes,bytes,bytes)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "createLOAN"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createLOAN",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "createLOAN", data: BytesLike): Result;

  events: {};
}

export interface IPWNSimpleLoan extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPWNSimpleLoanInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createLOAN(
      loanTermsFactoryContract: PromiseOrValue<string>,
      loanTermsFactoryData: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      loanAssetPermit: PromiseOrValue<BytesLike>,
      collateralPermit: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createLOAN(
    loanTermsFactoryContract: PromiseOrValue<string>,
    loanTermsFactoryData: PromiseOrValue<BytesLike>,
    signature: PromiseOrValue<BytesLike>,
    loanAssetPermit: PromiseOrValue<BytesLike>,
    collateralPermit: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createLOAN(
      loanTermsFactoryContract: PromiseOrValue<string>,
      loanTermsFactoryData: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      loanAssetPermit: PromiseOrValue<BytesLike>,
      collateralPermit: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    createLOAN(
      loanTermsFactoryContract: PromiseOrValue<string>,
      loanTermsFactoryData: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      loanAssetPermit: PromiseOrValue<BytesLike>,
      collateralPermit: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createLOAN(
      loanTermsFactoryContract: PromiseOrValue<string>,
      loanTermsFactoryData: PromiseOrValue<BytesLike>,
      signature: PromiseOrValue<BytesLike>,
      loanAssetPermit: PromiseOrValue<BytesLike>,
      collateralPermit: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
