/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPWNSimpleLoanListOffer,
  IPWNSimpleLoanListOfferInterface,
} from "./IPWNSimpleLoanListOffer";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "enum MultiToken.Category",
            name: "collateralCategory",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "collateralAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "collateralId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "collateralAmount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "loanAssetAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "loanAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "loanYield",
            type: "uint256",
          },
          {
            internalType: "uint32",
            name: "duration",
            type: "uint32",
          },
          {
            internalType: "uint40",
            name: "expiration",
            type: "uint40",
          },
          {
            internalType: "address",
            name: "borrower",
            type: "address",
          },
          {
            internalType: "address",
            name: "lender",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isPersistent",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
        ],
        internalType: "struct IPWNSimpleLoanListOffer.Offer",
        name: "offer",
        type: "tuple",
      },
    ],
    name: "encodeLoanTermsFactoryData",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "enum MultiToken.Category",
            name: "collateralCategory",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "collateralAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "collateralId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "collateralAmount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "loanAssetAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "loanAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "loanYield",
            type: "uint256",
          },
          {
            internalType: "uint32",
            name: "duration",
            type: "uint32",
          },
          {
            internalType: "uint40",
            name: "expiration",
            type: "uint40",
          },
          {
            internalType: "address",
            name: "borrower",
            type: "address",
          },
          {
            internalType: "address",
            name: "lender",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isPersistent",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
        ],
        internalType: "struct IPWNSimpleLoanListOffer.Offer",
        name: "offer",
        type: "tuple",
      },
    ],
    name: "getOfferHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPWNSimpleLoanListOffer__factory {
  static readonly abi = _abi;
  static createInterface(): IPWNSimpleLoanListOfferInterface {
    return new utils.Interface(_abi) as IPWNSimpleLoanListOfferInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPWNSimpleLoanListOffer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPWNSimpleLoanListOffer;
  }
}
